version: 1
services:
  telegram-bot:
    env: python
    build:
      command: pip install -r requirements.txt
    run:
      command: python bot.py
    envs:
      BOT_TOKEN:
        value: "8516803747:AAE5ZJ4sDjx3xIXZ91TF1FHQ5ii7tkRQBoc"
      CHANNEL_ID:
        value: "@testing2958"